/** @type {import('tailwindcss').Config} */
// GENERATED by scripts/tailwind-precompile.py - rerun that rather than hand-editing.
// Build: <tailwindcss> -c tailwind.config.js -i src/input.css -o styles.css --minify
// Replaces the runtime cdn.tailwindcss.com JIT compiler with a precompiled stylesheet.
// Any class added to this site LATER needs a rebuild or it will not exist in the CSS.
module.exports = {
    theme: {
      extend: {
        colors: {
          d: {
            "950": "#ffffff",
            "900": "#f7f7f8",
            "800": "#f0f0f0",
            "700": "#e8e8e8",
            "600": "#e0e0e0",
          },
          r: {
            DEFAULT: "#CC0000",
            dark: "#990000",
            light: "#E61A1A",
          },
          steel: {
            DEFAULT: "#4f6f87",
            dark: "#3d5a6e",
            light: "#6a8da6",
          },
          g: {
            DEFAULT: "#666666",
            light: "#888888",
          },
          lawn: {
            DEFAULT: "#3a7d44",
            dark: "#2a5e32",
            deep: "#1a3f20",
            light: "#4a9d56",
          },
        },
        fontFamily: {
          display: ["\"Teko\"", "sans-serif"],
          body: ["\"Inter\"", "sans-serif"],
        },
      },
    },
    content: ["./*.html"],
  }
